import { Navbar } from "@/components/navbar";

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-white text-zinc-900 selection:bg-zinc-100">
      <Navbar showAuth={true} />
      <div className="container mx-auto max-w-3xl py-12 px-4 lg:py-24">
        <h1 className="mb-8 text-4xl font-bold tracking-tight text-zinc-900 sm:text-5xl">Terms of Service</h1>
        <div className="prose prose-lg prose-zinc max-w-none text-zinc-500 selection:bg-zinc-100 prose-headings:font-bold prose-headings:tracking-tight prose-headings:text-zinc-900">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing and using Pine ("the Service"), you accept and agree to be bound by the terms and provision of this agreement.
          </p>

          <h2>2. Use License</h2>
          <p>
            Permission is granted to temporarily access the materials (information or software) on Pine's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title.
          </p>

          <h2>3. User Accounts</h2>
          <p>
            To access certain features of the Service, you may be required to register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate, current, and complete.
          </p>

          <h2>4. Content Liability</h2>
          <p>
            You are responsible for the content you generate using our AI services. Pine is not liable for any content generated by users or the AI models.
          </p>

          <h2>5. Termination</h2>
          <p>
            We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          </p>

          <h2>6. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. What constitutes a material change will be determined at our sole discretion.
          </p>

          <h2>7. Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us.
          </p>
        </div>
      </div>
    </div>
  );
}
